using System;
using Content.Shared.Nuke;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
namespace Content.Client._White.Lua.UI

{
    [GenerateTypedNameReferences]
    public sealed partial class LuaScriptingWindow : DefaultWindow
    {
        public event Action<int>? OnKeypadButtonPressed;
        public event Action? OnClearButtonPressed;
        public event Action? OnEnterButtonPressed;

        public LuaScriptingWindow()
        {
            RobustXamlLoader.Load(this);
        }

        public void UpdateState()
        {

        }
}
